name: frontend
description: "Flutter frontend for trash map"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  # HTTP通信（Flaskサーバーとの連携用）
  http: ^1.2.0
  # カメラ・写真選択機能
  image_picker: ^1.0.7
  # 通知機能
  flutter_local_notifications: ^17.2.1
  # Google Maps（地図表示）
  google_maps_flutter: ^2.14.0
  # ローカル保存
  shared_preferences: ^2.2.2
  # iOS風アイコン
  cupertino_icons: ^1.0.8
  timezone: ^0.9.4
  csv: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/schedules.csv
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Gem2.png" # 保存した画像のパス
  min_sdk_android: 21